import React from 'react';
import {
  MdWifi,
  MdPool,
  MdAcUnit,
  MdKitchen,
  MdRestaurant,
  MdTv,
  MdHotTub,
  MdLocalParking,
  MdSportsTennis,
  MdSpa,
  MdWaterDrop,
  MdCoffeeMaker,
  MdLocalDrink,
  MdLock,
  MdCheckroom,
  MdFlight,
  MdFitnessCenter,
  MdEventBusy,
  MdCalendarMonth,
  MdDelete,
  MdCalendarToday,
  MdCheckCircle,
  MdError,
  MdSearch,
  MdClose,
  MdInbox,
  MdChevronRight,
  MdArrowBack,
  MdPerson,
  MdReceipt,
  MdHistoryEdu,
  MdPayments,
  MdEditNote,
  MdWarning,
  MdTimeline,
  MdVisibility,
  MdVisibilityOff,
  MdDeleteForever,
  MdAdd,
  MdTrendingUp,
  MdVilla,
  MdMenu,
  MdNotifications,
  MdMail,
  MdLogout,
  MdHotel,
  MdKingBed,
  MdSingleBed,
  MdBathtub,
  MdShower,
  MdDirectionsCar,
  MdDirectionsBike,
  MdLocalAirport,
  MdBeachAccess,
  MdLocalDining,
  MdLocalCafe,
  MdLocalBar,
  MdRoomService,
  MdCleaningServices,
  MdDryCleaning,
  MdLocalLaundryService,
  MdIron,
  MdMicrowave,
  MdBlender,
  MdCoffee,
  MdWineBar,
  MdSmokingRooms,
  MdSmokeFree,
  MdPets,
  MdChildFriendly,
  MdFamilyRestroom,
  MdAccessible,
  MdElevator,
  MdStairs,
  MdBalcony,
  MdDeck,
  MdOutdoorGrill,
  MdFireplace,
  MdFireExtinguisher,
  MdMedicalServices,
  MdLocalHospital,
  MdLocalPharmacy,
  MdLocalPolice,
  MdDirectionsTransit,
  MdDirectionsBus,
  MdDirectionsRailway,
  MdLocalTaxi,
  MdMap,
  MdLocationOn,
  MdNearMe,
  MdExplore,
  MdTerrain,
  MdPark,
  MdForest,
  MdNature,
  MdNaturePeople,
  MdLandscape,
  MdSunny,
  MdWbSunny,
  MdNightsStay,
  MdStar,
  MdStarHalf,
  MdStarOutline,
  MdReviews,
  MdRateReview,
  MdThumbUp,
  MdThumbDown,
  MdFavorite,
  MdFavoriteBorder,
  MdShare,
  MdSend,
  MdChat,
  MdForum,
  MdPhone,
  MdCall,
  MdEmail,
  MdContactSupport,
  MdHelp,
  MdInfo,
  MdSettings,
  MdBuild,
  MdTune,
  MdSort,
  MdFilterList,
  MdMoreVert,
  MdMoreHoriz,
  MdApps,
  MdGridView,
  MdList,
  MdViewList,
  MdViewModule,
  MdViewQuilt,
  MdDashboard,
  MdHome,
  MdWork,
  MdSchool,
  MdStore,
  MdBusiness,
  MdApartment,
  MdHouse,
  MdCottage,
  MdCabin,
  MdChalet,
  MdBungalow,
  MdGite,
  MdHolidayVillage,
  MdCarRental,
  MdDirectionsBoat,
  MdFlightTakeoff,
  MdFlightLand,
  MdLuggage,
  MdNoLuggage,
  MdAirplaneTicket,
  MdConfirmationNumber,
  MdReceiptLong,
  MdArticle,
  MdDescription,
  MdAssignment,
  MdEvent,
  MdDateRange,
  MdSchedule,
  MdWatchLater,
  MdTimer,
  MdAlarm,
  MdAlarmOn,
  MdAlarmOff,
  MdSnooze,
  MdLightbulb,
  MdHighlight,
  MdWbIncandescent,
  MdFlare,
  MdFlashOn,
  MdFlashOff,
  MdFlashAuto,
  MdCameraAlt,
  MdPhotoCamera,
  MdVideocam,
  MdMic,
  MdVolumeUp,
  MdVolumeDown,
  MdVolumeMute,
  MdVolumeOff,
  MdPlayArrow,
  MdPause,
  MdStop,
  MdFastForward,
  MdFastRewind,
  MdSkipNext,
  MdSkipPrevious,
  MdShuffle,
  MdRepeat,
  MdMusicNote,
  MdLibraryMusic,
  MdMovie,
  MdLocalMovies,
  MdTheaters,
  MdOndemandVideo,
  MdTvOff,
  MdComputer,
  MdLaptop,
  MdSmartphone,
  MdTablet,
  MdWatch,
  MdDesktopMac,
  MdDesktopWindows,
  MdMouse,
  MdKeyboard,
  MdSpeaker,
  MdHeadset,
  MdHeadsetMic,
  MdRouter,
  MdCast,
  MdCastConnected,
  MdAirplay,
  MdPrint,
  MdPictureAsPdf,
  MdFolder,
  MdFolderOpen,
  MdCloud,
  MdCloudUpload,
  MdCloudDownload,
  MdCloudDone,
  MdBackup,
  MdSync,
  MdSyncProblem,
  MdAutorenew,
  MdRefresh,
  MdUpdate,
  MdLoop,
  MdUndo,
  MdRedo,
  MdReply,
  MdReplyAll,
  MdForward,
  MdArchive,
  MdUnarchive,
  MdDeleteOutline,
  MdSave,
  MdSaveAlt,
  MdFileDownload,
  MdFileUpload,
  MdAttachment,
  MdLink,
  MdAddLink,
  MdInsertLink,
  MdInsertPhoto,
  MdInsertDriveFile,
  MdInsertChart,
  MdInsertEmoticon,
  MdEmojiEmotions,
  MdMood,
  MdMoodBad,
  MdSentimentSatisfied,
  MdSentimentDissatisfied,
  MdSentimentVerySatisfied,
  MdSentimentVeryDissatisfied
} from 'react-icons/md';

export const iconMap = {
  'wifi': MdWifi,
  'pool': MdPool,
  'ac_unit': MdAcUnit,
  'kitchen': MdKitchen,
  'restaurant': MdRestaurant,
  'tv': MdTv,
  'hot_tub': MdHotTub,
  'local_parking': MdLocalParking,
  'sports_tennis': MdSportsTennis,
  'spa': MdSpa,
  'water_drop': MdWaterDrop,
  'coffee_maker': MdCoffeeMaker,
  'local_drink': MdLocalDrink,
  'lock': MdLock,
  'checkroom': MdCheckroom,
  'flight': MdFlight,
  'fitness_center': MdFitnessCenter,
  'event_busy': MdEventBusy,
  'calendar_month': MdCalendarMonth,
  'delete': MdDelete,
  'calendar_today': MdCalendarToday,
  'check_circle': MdCheckCircle,
  'error': MdError,
  'search': MdSearch,
  'close': MdClose,
  'inbox': MdInbox,
  'chevron_right': MdChevronRight,
  'arrow_back': MdArrowBack,
  'person': MdPerson,
  'receipt': MdReceipt,
  'history_edu': MdHistoryEdu,
  'payments': MdPayments,
  'edit_note': MdEditNote,
  'warning': MdWarning,
  'timeline': MdTimeline,
  'visibility': MdVisibility,
  'visibility_off': MdVisibilityOff,
  'delete_forever': MdDeleteForever,
  'add': MdAdd,
  'trending_up': MdTrendingUp,
  'villa': MdVilla,
  'menu': MdMenu,
  'notifications': MdNotifications,
  'mail': MdMail,
  'logout': MdLogout,
  'hotel': MdHotel,
  'king_bed': MdKingBed,
  'single_bed': MdSingleBed,
  'bathtub': MdBathtub,
  'shower': MdShower,
  'directions_car': MdDirectionsCar,
  'directions_bike': MdDirectionsBike,
  'local_airport': MdLocalAirport,
  'beach_access': MdBeachAccess,
  'local_dining': MdLocalDining,
  'local_cafe': MdLocalCafe,
  'local_bar': MdLocalBar,
  'room_service': MdRoomService,
  'cleaning_services': MdCleaningServices,
  'dry_cleaning': MdDryCleaning,
  'local_laundry_service': MdLocalLaundryService,
  'iron': MdIron,
  'microwave': MdMicrowave,
  'blender': MdBlender,
  'coffee': MdCoffee,
  'wine_bar': MdWineBar,
  'smoking_rooms': MdSmokingRooms,
  'smoke_free': MdSmokeFree,
  'pets': MdPets,
  'child_friendly': MdChildFriendly,
  'family_restroom': MdFamilyRestroom,
  'accessible': MdAccessible,
  'elevator': MdElevator,
  'stairs': MdStairs,
  'balcony': MdBalcony,
  'deck': MdDeck,
  'outdoor_grill': MdOutdoorGrill,
  'fireplace': MdFireplace,
  'fire_extinguisher': MdFireExtinguisher,
  'medical_services': MdMedicalServices,
  'local_hospital': MdLocalHospital,
  'local_pharmacy': MdLocalPharmacy,
  'local_police': MdLocalPolice,
  'directions_transit': MdDirectionsTransit,
  'directions_bus': MdDirectionsBus,
  'directions_railway': MdDirectionsRailway,
  'local_taxi': MdLocalTaxi,
  'map': MdMap,
  'location_on': MdLocationOn,
  'near_me': MdNearMe,
  'explore': MdExplore,
  'terrain': MdTerrain,
  'park': MdPark,
  'forest': MdForest,
  'nature': MdNature,
  'nature_people': MdNaturePeople,
  'landscape': MdLandscape,
  'sunny': MdSunny,
  'wb_sunny': MdWbSunny,
  'nights_stay': MdNightsStay,
  'star': MdStar,
  'star_half': MdStarHalf,
  'star_outline': MdStarOutline,
  'reviews': MdReviews,
  'rate_review': MdRateReview,
  'thumb_up': MdThumbUp,
  'thumb_down': MdThumbDown,
  'favorite': MdFavorite,
  'favorite_border': MdFavoriteBorder,
  'share': MdShare,
  'send': MdSend,
  'chat': MdChat,
  'forum': MdForum,
  'phone': MdPhone,
  'call': MdCall,
  'email': MdEmail,
  'contact_support': MdContactSupport,
  'help': MdHelp,
  'info': MdInfo,
  'settings': MdSettings,
  'build': MdBuild,
  'tune': MdTune,
  'sort': MdSort,
  'filter_list': MdFilterList,
  'more_vert': MdMoreVert,
  'more_horiz': MdMoreHoriz,
  'apps': MdApps,
  'grid_view': MdGridView,
  'list': MdList,
  'view_list': MdViewList,
  'view_module': MdViewModule,
  'view_quilt': MdViewQuilt,
  'dashboard': MdDashboard,
  'home': MdHome,
  'work': MdWork,
  'school': MdSchool,
  'store': MdStore,
  'business': MdBusiness,
  'apartment': MdApartment,
  'house': MdHouse,
  'cottage': MdCottage,
  'cabin': MdCabin,
  'chalet': MdChalet,
  'bungalow': MdBungalow,
  'gite': MdGite,
  'holiday_village': MdHolidayVillage,
  'car_rental': MdCarRental,
  'directions_boat': MdDirectionsBoat,
  'flight_takeoff': MdFlightTakeoff,
  'flight_land': MdFlightLand,
  'luggage': MdLuggage,
  'no_luggage': MdNoLuggage,
  'airplane_ticket': MdAirplaneTicket,
  'confirmation_number': MdConfirmationNumber,
  'receipt_long': MdReceiptLong,
  'article': MdArticle,
  'description': MdDescription,
  'assignment': MdAssignment,
  'event': MdEvent,
  'date_range': MdDateRange,
  'schedule': MdSchedule,
  'watch_later': MdWatchLater,
  'timer': MdTimer,
  'alarm': MdAlarm,
  'alarm_on': MdAlarmOn,
  'alarm_off': MdAlarmOff,
  'snooze': MdSnooze,
  'lightbulb': MdLightbulb,
  'highlight': MdHighlight,
  'wb_incandescent': MdWbIncandescent,
  'flare': MdFlare,
  'flash_on': MdFlashOn,
  'flash_off': MdFlashOff,
  'flash_auto': MdFlashAuto,
  'camera_alt': MdCameraAlt,
  'photo_camera': MdPhotoCamera,
  'videocam': MdVideocam,
  'mic': MdMic,
  'volume_up': MdVolumeUp,
  'volume_down': MdVolumeDown,
  'volume_mute': MdVolumeMute,
  'volume_off': MdVolumeOff,
  'play_arrow': MdPlayArrow,
  'pause': MdPause,
  'stop': MdStop,
  'fast_forward': MdFastForward,
  'fast_rewind': MdFastRewind,
  'skip_next': MdSkipNext,
  'skip_previous': MdSkipPrevious,
  'shuffle': MdShuffle,
  'repeat': MdRepeat,
  'music_note': MdMusicNote,
  'library_music': MdLibraryMusic,
  'movie': MdMovie,
  'local_movies': MdLocalMovies,
  'theaters': MdTheaters,
  'ondemand_video': MdOndemandVideo,
  'tv_off': MdTvOff,
  'computer': MdComputer,
  'laptop': MdLaptop,
  'smartphone': MdSmartphone,
  'tablet': MdTablet,
  'watch': MdWatch,
  'desktop_mac': MdDesktopMac,
  'desktop_windows': MdDesktopWindows,
  'mouse': MdMouse,
  'keyboard': MdKeyboard,
  'speaker': MdSpeaker,
  'headset': MdHeadset,
  'headset_mic': MdHeadsetMic,
  'router': MdRouter,
  'cast': MdCast,
  'cast_connected': MdCastConnected,
  'airplay': MdAirplay,
  'print': MdPrint,
  'picture_as_pdf': MdPictureAsPdf,
  'folder': MdFolder,
  'folder_open': MdFolderOpen,
  'cloud': MdCloud,
  'cloud_upload': MdCloudUpload,
  'cloud_download': MdCloudDownload,
  'cloud_done': MdCloudDone,
  'backup': MdBackup,
  'sync': MdSync,
  'sync_problem': MdSyncProblem,
  'autorenew': MdAutorenew,
  'refresh': MdRefresh,
  'update': MdUpdate,
  'loop': MdLoop,
  'undo': MdUndo,
  'redo': MdRedo,
  'reply': MdReply,
  'reply_all': MdReplyAll,
  'forward': MdForward,
  'archive': MdArchive,
  'unarchive': MdUnarchive,
  'delete_outline': MdDeleteOutline,
  'save': MdSave,
  'save_alt': MdSaveAlt,
  'file_download': MdFileDownload,
  'file_upload': MdFileUpload,
  'attachment': MdAttachment,
  'link': MdLink,
  'add_link': MdAddLink,
  'insert_link': MdInsertLink,
  'insert_photo': MdInsertPhoto,
  'insert_drive_file': MdInsertDriveFile,
  'insert_chart': MdInsertChart,
  'insert_emoticon': MdInsertEmoticon,
  'emoji_emotions': MdEmojiEmotions,
  'mood': MdMood,
  'mood_bad': MdMoodBad,
  'sentiment_satisfied': MdSentimentSatisfied,
  'sentiment_dissatisfied': MdSentimentDissatisfied,
  'sentiment_very_satisfied': MdSentimentVerySatisfied,
  'sentiment_very_dissatisfied': MdSentimentVeryDissatisfied,
};

export const IconRenderer = ({ name, className = '', ...props }) => {
  const IconComponent = iconMap[name];
  
  if (!IconComponent) {
    return <MdCheckCircle className={className} {...props} />;
  }

  return <IconComponent className={className} {...props} />;
};

export const AVAILABLE_ICONS = Object.keys(iconMap);
